name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
permissions:
    contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Install yq
      run: sudo apt-get install -y jq && sudo wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 && sudo chmod +x /usr/bin/yq

    - name: Build and Push Docker Image
      run: |
        # Use GitHub SHA as image tag
        IMAGE="${{ secrets.DOCKER_USERNAME }}/gitops-app:${GITHUB_RUN_NUMBER}"
        echo "Using IMAGE=$IMAGE"

        # Build & push image
        docker buildx build --platform linux/amd64 -t $IMAGE . --push

        # Update Kubernetes deployment with new image
        yq -i '.spec.template.spec.containers[0].image = env(IMAGE)' k8s/deployment.yaml

        # Commit the updated deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update deployment to image $IMAGE"
        git push origin main


        

    
      
 


